spring:
  config:
    import: 'optional:configserver:'
  output:
    ansi:
      enabled: ALWAYS
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: '*****'

email:
  from: 'paulo.h.g.pimentel@gmail.com'